enum ActionTypes {
  RESET_GAME = 'RESET_GAME',
  FLIP_ALL_CARDS_TO_BACK = 'FLIP_ALL_CARDS_TO_BACK',
  FLIP_CARD = 'FLIP_CARD',
  MATCH_TWO_CARDS = 'MATCH_TWO_CARDS',
  LOCK_FLIP = 'LOCK_FLIP',
  WIN_GAME = 'WIN_GAME',
}

export default ActionTypes;
